<?php

/**
 * @file
 * Adds the Javascript to the bottom of Drupal page.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function adobe_analytics_help($route_name, RouteMatchInterface $route_match) {

  switch ($route_name) {
    case 'help.page.adobe_analytics':
      return ['#markup' => '<p>' . t('Settings for AdobeAnalytics.') . '</p>'];
  }
}

/**
 * Implements hook_theme().
 */
function adobe_analytics_theme($existing, $type, $theme, $path) {
  return [
    'analytics_code' => [
      'variables' => [
        'js_file_location' => NULL,
        'formatted_vars' => NULL,
        'version' => NULL,
        'image_location' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_page_bottom().
 */
function adobe_analytics_page_bottom(&$variables) {
  $variables['adobe_analytics'] = [
    '#lazy_builder' => ['adobe_analytics.variable_formatter:renderMarkup', []],
    '#create_placeholder' => TRUE,
    '#cache' => [
      'contexts' => ['user.roles'],
      'tags' => \Drupal::config('adobe_analytics.settings')->getCacheTags(),
    ],
  ];
}
